apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-pod
  labels:
    run: my-nginx
spec:
  containers:
  - name: my-ubuntu
    image: ubuntu
    command: ["/bin/bash", "-ec", "while :; do echo '.'; sleep 5 ; done"]
    ports:
    - containerPort: 80